#!/bin/bash
if [[ "$OSTYPE" == "linux-gnu" ]]; then
        envfile="./envs/env_linux.yml"
elif [[ "$OSTYPE" == "darwin"* ]]; then
        envfile="./envs/env_darwin.yml"
fi

if echo "$(conda info --envs)" | grep -q "llsmvis"
then
  echo conda environment 'llsmvis' already exists, update? \(yes/no\)
  read v
  if [[ $v == 'yes' ]]
  then
    echo updating existing llsmvis environment
    conda env update -f $envfile
    echo "now activating llsmvis and add the kernel spec to jupyter notebook"
    conda activate llsmvis
    ipython kernel install --user --name=llsmvis

  else
  echo -- no action performed.
  fi
else
  echo creating conda environment 'llsmvis'
  conda env create -f $envfile
    echo "now activating llsmvis and add the kernel spec to jupyter notebook"
    conda activate llsmvis
    ipython kernel install --user --name=llsmvis
fi
