#!/bin/bash
if [[ "$OSTYPE" == "linux-gnu" ]]; then
        envfile="./envs/env_linux.yml"
elif [[ "$OSTYPE" == "darwin"* ]]; then
        envfile="./envs/env_darwin.yml"
fi

if echo "$(conda info --envs)" | grep -q "llsm"
then
  echo conda environment 'llsm' already exists, update? \(yes/no\)
  read v
  if [[ $v == 'yes' ]]
  then
    echo updating existing llsm environment
    conda env update -f $envfile
  else
  echo -- no action performed.
  fi
else
  echo creating conda environment 'llsm'
  conda env create -f $envfile
fi
