APP:
  VERBOSE: True
  #add settings here

FTP: 
  PORT: 2121
  IP: 192.168.0.129
  FTP_USER: myuser
  FTP_PASSWORD: myuser
  SERVERNAME: Fiddlesticks LLSM FTP SERVER
  FTP_DIRECTORY: C:\Users\miao1\Development\demo_data\sync_source
