#!/bin/bash
# This bash script checks, organizes, generates and submits slurm jobs to perform idx conversion ofr ViSUS
#
#
# The resultant python and slurm scripts are placed in the 'JOBS_idx' folder under the current directory.

echo 'startig time'
echo date
mkdir jobs_idx
mkdir results_idx

pythonpath=$(echo $(which python) | sed 's/\//\\\//g')
homepath=$(echo $(echo ~) | sed 's/\//\\\//g')

##### identify and prepare single node jobs using sbatch for each file head
slurms=()
for i in $(ls *.txt) # check all txt files
do
    if [[ $i == *_Settings.txt ]] # consider only the Setting.txt files, each corresponds to one 4D dataset.
    then

    # get the file head of the 4D datasete
    echo prep for $i

    # define filehead string
    filehead=${i:0:${#i}-13}

    # define path string, handle the special characters "/" in the path.
    fpath=$(echo $(pwd) | sed 's/\//\\\//g')

    # define seed file path for the executabllse python script and the slurm (shell)
    seedpy=$(echo ~/llsmvis/tools/idxconv.seed)
    if [ -f $seedpy ]; then :; else echo $seedpy not found; fi
    seedsl=$(echo ~/llsmvis/tools/slurm.seed)
    if [ -f $seedsl ]; then :; else echo $seedsl not found; fi

    # define output file path for the executable python script and the slurm (shell)
    foutpy="./jobs_idx/idxconv_"$filehead".py"
    foutsl="./jobs_idx/slurm_"$filehead
    # prepare the corresponding executable python script
    sed -e "s/FPATH/\"$fpath\"/g" -e "s/FHEAD/\"$filehead\"/g" \
    -e "s/\[WHICHPYTHON\]/$pythonpath/g" -e "s/\[HOME\]/\"$homepath\"/g" $seedpy > $foutpy

    # prepare the corresponding slurm
    sed "s/\[EXECUTABLE\]/$fpath\/jobs_idx\/idxconv_"$filehead".py/g" $seedsl > $foutsl
    chmod u+rwx $foutpy
    chmod u+rwx $foutsl
    slurms+=(slurm_$filehead)
    fi
done

#### Launch single node jobs using sbatch for each
echo submit all jobs? \(y/[n]\)
read v
if [[ $v == "y" ]]
then
  cd jobs_idx
  for s in ${slurms[@]}
  do
    echo submitting $s
    sbatch $s
  done
  cd ..
  echo all job submitted.
else
  echo all job are prepared in ./jobs_idx
  echo
fi