#!/bin/bash

function tmllsmvis.move-all-mip
{
  echo $# input arguments.
  if [ $# -eq 0 ]
  then
    echo Syntax:
    echo tmllsmvis.move-all-mip [destimation folder]
    echo This will copy the folders under the current directory into [destimation folder] and copy only the MIP files.
    echo It should be used with the llsmvis package after the getdsk command, and used inside the folder resutls_dsk.
    echo
  fi

  if [ $# -ge 2 ]
  then
    echo Sorry, too many input arguments. Type tmpllsmvis.move-all-mip for syntax
  fi

  if [ $# -eq 1 ]
  then
  mkdir $1
  scp *.txt $1/.
  for i in $(ls)
  do
    if [[ $i == *deskewed ]]
    then
      mkdir $1/$i
      cd $i
      for j in $(ls)
      do
        if [[ $j == MIP* ]]
        then
          scp $j $1/$i/$j
        fi
      done
      cd ..
    fi
  done
  fi
}